{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.eums",
    "module": "eums_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "eums_profile-1.0.aar",
          "url": "eums_profile-1.0.aar",
          "size": 46977,
          "sha512": "028aa5cd497a4b7e66f53f8afdb74701b199012700e5c9d30491aaff0756482aa24c79e73b18c4f36817b7c56e7926783b7f2e0bfe62c0f9be9ba2cb366951d5",
          "sha256": "cb87dea9ab49a45d537aa17365d5f78e8611a7355d34a136d29d7ca23ddd9af0",
          "sha1": "4c3f5319c4d14d13db665aeb151c303a8e58cc38",
          "md5": "36f4c065be3a960146e55ef1ce8fe84e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.3.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_overlay_window",
          "module": "flutter_overlay_window_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fr.g123k.deviceapps",
          "module": "device_apps_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.devicelocale",
          "module": "devicelocale_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "in.jvapps.disable_battery_optimization",
          "module": "disable_battery_optimization_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.spencerccf.app_settings",
          "module": "app_settings_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_component",
          "module": "flutter_component_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "eums_profile-1.0.aar",
          "url": "eums_profile-1.0.aar",
          "size": 46977,
          "sha512": "028aa5cd497a4b7e66f53f8afdb74701b199012700e5c9d30491aaff0756482aa24c79e73b18c4f36817b7c56e7926783b7f2e0bfe62c0f9be9ba2cb366951d5",
          "sha256": "cb87dea9ab49a45d537aa17365d5f78e8611a7355d34a136d29d7ca23ddd9af0",
          "sha1": "4c3f5319c4d14d13db665aeb151c303a8e58cc38",
          "md5": "36f4c065be3a960146e55ef1ce8fe84e"
        }
      ]
    }
  ]
}
