// Autogenerated from Pigeon (v1.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BKBook;
@class BKThumbnail;

@interface BKBook : NSObject
@property(nonatomic, copy, nullable) NSString *memBirth;
@property(nonatomic, copy, nullable) NSString *memGen;
@property(nonatomic, copy, nullable) NSString *memRegion;
@property(nonatomic, copy, nullable) NSString *memId;
@property(nonatomic, copy, nullable) NSString *firebaseKey;
@end


/// The codec used by BKFlutterBookApi.
NSObject<FlutterMessageCodec> *BKFlutterBookApiGetCodec(void);

@interface BKFlutterBookApi : NSObject
- (instancetype)initWithBinaryMessenger:
    (id<FlutterBinaryMessenger>)binaryMessenger;
- (void)displayBookDetailsBook:(BKBook *)book
                    completion:(void (^)(NSError *_Nullable))completion;
@end
/// The codec used by BKHostBookApi.
NSObject<FlutterMessageCodec> *BKHostBookApiGetCodec(void);

@protocol BKHostBookApi
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
//- (void)finishEditingBookBook:(BKBook *)book
//                        error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BKHostBookApiSetup(id<FlutterBinaryMessenger> binaryMessenger,
                               NSObject<BKHostBookApi> *_Nullable api);

NS_ASSUME_NONNULL_END
