// Autogenerated from Pigeon (v1.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "api.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result,
                                                FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
      @"code" : (error.code ? error.code : [NSNull null]),
      @"message" : (error.message ? error.message : [NSNull null]),
      @"details" : (error.details ? error.details : [NSNull null]),
    };
  }
  return @{
    @"result" : (result ? result : [NSNull null]),
    @"error" : errorDict,
  };
}

@interface BKBook ()
+ (BKBook *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation BKBook
+ (BKBook *)fromMap:(NSDictionary *)dict {
  BKBook *result = [[BKBook alloc] init];
  result.memBirth = dict[@"memBirth"];
  if ((NSNull *)result.memBirth == [NSNull null]) {
    result.memBirth = nil;
  }
  result.memGen = dict[@"memGen"];
  if ((NSNull *)result.memGen == [NSNull null]) {
    result.memGen = nil;
  }
  result.memRegion = dict[@"memRegion"];
  if ((NSNull *)result.memRegion == [NSNull null]) {
    result.memRegion = nil;
  }
  result.memId = dict[@"memId"];
  if ((NSNull *)result.memId == [NSNull null]) {
    result.memId = nil;
  }
  result.firebaseKey = dict[@"firebaseKey"];
  if ((NSNull *)result.firebaseKey == [NSNull null]) {
    result.firebaseKey = nil;
  }
  
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary
      dictionaryWithObjectsAndKeys:
          (self.memBirth ? self.memBirth : [NSNull null]), @"memBirth",
          (self.memGen ? self.memGen : [NSNull null]), @"memGen",
          (self.memRegion ? self.memRegion : [NSNull null]), @"memRegion",
          (self.memId ? self.memId : [NSNull null]), @"memId",
          (self.firebaseKey ? self.firebaseKey : [NSNull null]), @"firebaseKey", nil];
}
@end


@interface BKFlutterBookApiCodecReader : FlutterStandardReader
@end
@implementation BKFlutterBookApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
  case 128:
    return [BKBook fromMap:[self readValue]];

  default:
    return [super readValueOfType:type];
  }
}
@end

@interface BKFlutterBookApiCodecWriter : FlutterStandardWriter
@end
@implementation BKFlutterBookApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[BKBook class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface BKFlutterBookApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation BKFlutterBookApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[BKFlutterBookApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[BKFlutterBookApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *BKFlutterBookApiGetCodec(void) {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    BKFlutterBookApiCodecReaderWriter *readerWriter =
        [[BKFlutterBookApiCodecReaderWriter alloc] init];
    s_sharedObject =
        [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}

@interface BKFlutterBookApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation BKFlutterBookApi
- (instancetype)initWithBinaryMessenger:
    (NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}

- (void)displayBookDetailsBook:(BKBook *)arg_book
                    completion:(void (^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel = [FlutterBasicMessageChannel
      messageChannelWithName:
          @"dev.flutter.pigeon.FlutterBookApi.displayBookDetails"
             binaryMessenger:self.binaryMessenger
                       codec:BKFlutterBookApiGetCodec()];
  [channel sendMessage:@[ arg_book ]
                 reply:^(id reply) {
                   completion(nil);
                 }];
}
@end
@interface BKHostBookApiCodecReader : FlutterStandardReader
@end
@implementation BKHostBookApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
  case 128:
    return [BKBook fromMap:[self readValue]];

  default:
    return [super readValueOfType:type];
  }
}
@end

@interface BKHostBookApiCodecWriter : FlutterStandardWriter
@end
@implementation BKHostBookApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[BKBook class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface BKHostBookApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation BKHostBookApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[BKHostBookApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[BKHostBookApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *BKHostBookApiGetCodec(void) {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    BKHostBookApiCodecReaderWriter *readerWriter =
        [[BKHostBookApiCodecReaderWriter alloc] init];
    s_sharedObject =
        [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}

void BKHostBookApiSetup(id<FlutterBinaryMessenger> binaryMessenger,
                        NSObject<BKHostBookApi> *api) {
  {
    FlutterBasicMessageChannel *channel = [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.HostOfferwallApi.cancel"
               binaryMessenger:binaryMessenger
                         codec:BKHostBookApiGetCodec()];
    if (api) {
      NSCAssert(
          [api respondsToSelector:@selector(cancelWithError:)],
          @"BKHostBookApi api doesn't respond to @selector(cancelWithError:)");
      [channel
          setMessageHandler:^(id _Nullable message, FlutterReply callback) {
            FlutterError *error;
            [api cancelWithError:&error];
            callback(wrapResult(nil, error));
          }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
//  {
//    FlutterBasicMessageChannel *channel = [FlutterBasicMessageChannel
//        messageChannelWithName:
//            @"dev.flutter.pigeon.HostBookApi.finishEditingBook"
//               binaryMessenger:binaryMessenger
//                         codec:BKHostBookApiGetCodec()];
//    if (api) {
//      NSCAssert([api respondsToSelector:@selector(finishEditingBookBook:
//                                                                  error:)],
//                @"BKHostBookApi api doesn't respond to "
//                @"@selector(finishEditingBookBook:error:)");
//      [channel
//          setMessageHandler:^(id _Nullable message, FlutterReply callback) {
//            NSArray *args = message;
//            BKBook *arg_book = args[0];
//            FlutterError *error;
//            [api finishEditingBookBook:arg_book error:&error];
//            callback(wrapResult(nil, error));
//          }];
//    } else {
//      [channel setMessageHandler:nil];
//    }
//  }
}
