{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.crashlytics",
    "module": "firebase_crashlytics_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_debug-1.0.aar",
          "url": "firebase_crashlytics_debug-1.0.aar",
          "size": 17349,
          "sha512": "898fdd0ec2baecd1a8ec1a0e0d05fe9ca961d114017e8d57a95c98da7bc31e6ea4721f6c9ea9c24be065062adaf142f3cfac5a97793057833491e4a884edd7d4",
          "sha256": "6405e3f60125970321f712d8391a67564f61cbb848fe6be0bd4d0883f0c43d77",
          "sha1": "56251d31e7b17e7ce0754ce756c049bdbeb950a7",
          "md5": "cee9757ace1c3f7150f66f7468b8219e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.3.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_debug-1.0.aar",
          "url": "firebase_crashlytics_debug-1.0.aar",
          "size": 17349,
          "sha512": "898fdd0ec2baecd1a8ec1a0e0d05fe9ca961d114017e8d57a95c98da7bc31e6ea4721f6c9ea9c24be065062adaf142f3cfac5a97793057833491e4a884edd7d4",
          "sha256": "6405e3f60125970321f712d8391a67564f61cbb848fe6be0bd4d0883f0c43d77",
          "sha1": "56251d31e7b17e7ce0754ce756c049bdbeb950a7",
          "md5": "cee9757ace1c3f7150f66f7468b8219e"
        }
      ]
    }
  ]
}
