{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_component",
    "module": "flutter_component_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_component_profile-1.0.aar",
          "url": "flutter_component_profile-1.0.aar",
          "size": 4938,
          "sha512": "bb6aa135619fb3cd4e195f70b1df23de784d0972beffad1f557b70542ca15900f699bef683dfbd27308ab580b588188a1f7eca3f19be0182a57f50575d298cd5",
          "sha256": "49fdf3ab915c3d9a7048ccfd7a5d8e244dbde9c0c63a19cc85ba72a93d260868",
          "sha1": "b5068bd256d747e91298a32526c433ba0f408175",
          "md5": "f5835638554b69fc86afd9f0e3d024f5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_component_profile-1.0.aar",
          "url": "flutter_component_profile-1.0.aar",
          "size": 4938,
          "sha512": "bb6aa135619fb3cd4e195f70b1df23de784d0972beffad1f557b70542ca15900f699bef683dfbd27308ab580b588188a1f7eca3f19be0182a57f50575d298cd5",
          "sha256": "49fdf3ab915c3d9a7048ccfd7a5d8e244dbde9c0c63a19cc85ba72a93d260868",
          "sha1": "b5068bd256d747e91298a32526c433ba0f408175",
          "md5": "f5835638554b69fc86afd9f0e3d024f5"
        }
      ]
    }
  ]
}
