{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_offerwall_module",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_component",
          "module": "flutter_component_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.geolocator",
          "module": "geolocator_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_overlay_window",
          "module": "flutter_overlay_window_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "id.flutter.flutter_background_service",
          "module": "flutter_background_service_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.spencerccf.app_settings",
          "module": "app_settings_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "in.jvapps.disable_battery_optimization",
          "module": "disable_battery_optimization_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.eums",
          "module": "eums_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.devicelocale",
          "module": "devicelocale_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fr.g123k.deviceapps",
          "module": "device_apps_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 33685497,
          "sha512": "2294e980e321dfc79cb1b949c216f7a4f4e92e8daf97a7c49c826f22c4a4a403edca077fddcf609ee9fb38a5a54d1a1fd95086002e274019d05a3d5f7375df28",
          "sha256": "c84102a5fc221ce6480d55ffd22e0757e15acb6957b04f60b174527c31bc4a53",
          "sha1": "ad143927ef50520beb4c43b4e0eabeebabfe64bc",
          "md5": "4c666f5f2cbfd466dd9448d15f6b84a2"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_component",
          "module": "flutter_component_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.geolocator",
          "module": "geolocator_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_overlay_window",
          "module": "flutter_overlay_window_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "id.flutter.flutter_background_service",
          "module": "flutter_background_service_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.spencerccf.app_settings",
          "module": "app_settings_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "in.jvapps.disable_battery_optimization",
          "module": "disable_battery_optimization_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.eums",
          "module": "eums_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.devicelocale",
          "module": "devicelocale_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fr.g123k.deviceapps",
          "module": "device_apps_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 33685497,
          "sha512": "2294e980e321dfc79cb1b949c216f7a4f4e92e8daf97a7c49c826f22c4a4a403edca077fddcf609ee9fb38a5a54d1a1fd95086002e274019d05a3d5f7375df28",
          "sha256": "c84102a5fc221ce6480d55ffd22e0757e15acb6957b04f60b174527c31bc4a53",
          "sha1": "ad143927ef50520beb4c43b4e0eabeebabfe64bc",
          "md5": "4c666f5f2cbfd466dd9448d15f6b84a2"
        }
      ]
    }
  ]
}
