{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.core",
    "module": "firebase_core_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_profile-1.0.aar",
          "url": "firebase_core_profile-1.0.aar",
          "size": 29048,
          "sha512": "99718cef07f632769e4bfd7c0a7ba5c57a6e4f0a6f5def9deb8e0faadae1aca12a4fe45b5b5b0774a69b1e605e416788b3442ea32108447772c23637a6118997",
          "sha256": "69a6fc40a605ff679c5aea0d3fccc003e2a5b023af975bd7c73719c6bdc98348",
          "sha1": "10554dce0f1603b59d2e8b6ae76bb119b61bcbac",
          "md5": "0a8464ff0064c2147a418f0909263d63"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.3.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_profile-1.0.aar",
          "url": "firebase_core_profile-1.0.aar",
          "size": 29048,
          "sha512": "99718cef07f632769e4bfd7c0a7ba5c57a6e4f0a6f5def9deb8e0faadae1aca12a4fe45b5b5b0774a69b1e605e416788b3442ea32108447772c23637a6118997",
          "sha256": "69a6fc40a605ff679c5aea0d3fccc003e2a5b023af975bd7c73719c6bdc98348",
          "sha1": "10554dce0f1603b59d2e8b6ae76bb119b61bcbac",
          "md5": "0a8464ff0064c2147a418f0909263d63"
        }
      ]
    }
  ]
}
